// The repertoire.
//
// The note data lives in ./scores, generated by tools/import-kern.mjs and
// tools/import-midi.mjs from published digital editions — Humdrum **kern
// editions of named printed sources, and Mutopia's LilyPond engravings. See
// scores/SOURCES.md for who made them.
//
// It used to be hand-typed from memory, which is fine for the eight bars of
// something everybody knows and hopeless for the rest: Für Elise was thirteen
// bars of a hundred and five, The Entertainer four of ninety-two. Worse, the
// hand each note belongs to was being guessed from its pitch, so any crossing
// of the hands was silently wrong. An edition keeps the two staves apart, so
// now that comes from the source as well.
//
// Chopsticks is the exception and says so: it is an oral tradition with no
// urtext to import, and its notes are written out below as an arrangement.

import { planGestures, spanFor } from './gesture'
import * as allaTurca from './scores/alla-turca'
import * as bachPrelude from './scores/bach-prelude'
import * as entertainer from './scores/entertainer'
import * as furElise from './scores/fur-elise'
import * as mapleLeaf from './scores/mapleleaf'
import * as minuetG from './scores/minuet-g'
import * as moonlight from './scores/moonlight'
import * as mountainKing from './scores/mountain-king'
import * as pathetique from './scores/pathetique'
import * as sonataFacile from './scores/sonata-facile'

export type NoteEv = {
  p: number   // midi pitch
  b: number   // start, in pulses (a "pulse" = one thing you mime)
  d: number   // duration, in pulses
  v: number   // 0..1 velocity
  h?: -1 | 1  // which hand plays it. -1 left, 1 right. Falls back to register.
}

export type Piece = {
  id: string
  title: string
  composer: string
  short: string        // surname only, for the tight menu row
  blurb: string
  pulseBpm: number      // suggested pulses (beats) per minute
  pulsesPerBar: number
  stride: number        // gestures advanced by one stroke of your hand
  /** where a stroke of your hand belongs, worked out from the score itself */
  gestures: number[]
  loopAt: number        // pulse count at which the take starts over
  release: number       // seconds of release ramp (pedal-ish feel)
  accent: string        // hex, drives the palette
  accent2: string
  resonance: number[]   // midi notes the strings ring in sympathy with
  notes: NoteEv[]
}

const STEP: Record<string, number> = { C: 0, D: 2, E: 4, F: 5, G: 7, A: 9, B: 11 }

/** "C#4" | "Bb2" | "Ds1" -> midi number (C4 = 60) */
export function m(name: string): number {
  const s = /^([A-G])([#sb]?)(-?\d)$/.exec(name.trim())
  if (!s) throw new Error(`bad note name: ${name}`)
  let v = STEP[s[1]]
  if (s[2] === '#' || s[2] === 's') v += 1
  if (s[2] === 'b') v -= 1
  return v + (parseInt(s[3], 10) + 1) * 12
}

// ------------------------------------------------------------- Chopsticks

/**
 * The Celebrated Chop Waltz, Euphemia Allen, 1877. Written to be played with
 * the sides of both hands, which makes it the one piece here that is *about*
 * having two of them — and the only one anybody has ever played as a duet on
 * purpose.
 */
function chopsticks(): NoteEv[] {
  const o: NoteEv[] = []
  const chop = (a: string, b: string, bar: number, v = 0.72) => {
    for (let k = 0; k < 3; k++) {
      o.push({ p: m(a), b: bar * 3 + k, d: 0.9, v: k === 0 ? v + 0.08 : v, h: 1 })
      o.push({ p: m(b), b: bar * 3 + k, d: 0.9, v: k === 0 ? v + 0.08 : v, h: 1 })
    }
  }
  const oom = (root: string, fifth: string, bar: number) => {
    o.push({ p: m(root), b: bar * 3, d: 1, v: 0.55, h: -1 })
    o.push({ p: m(fifth), b: bar * 3 + 1, d: 1, v: 0.4, h: -1 })
    o.push({ p: m(fifth), b: bar * 3 + 2, d: 1, v: 0.4, h: -1 })
  }

  const pairs: [string, string][] = [
    ['F4', 'G4'], ['F4', 'G4'], ['E4', 'G4'], ['E4', 'G4'],
    ['D4', 'B4'], ['D4', 'B4'], ['C4', 'E4'], ['C4', 'E4'],
  ]
  const bass: [string, string][] = [
    ['C2', 'G2'], ['C2', 'G2'], ['C2', 'G2'], ['C2', 'G2'],
    ['G2', 'D3'], ['G2', 'D3'], ['C2', 'G2'], ['C2', 'G2'],
  ]
  pairs.forEach(([a, b], i) => { chop(a, b, i); oom(bass[i][0], bass[i][1], i) })

  // the little turn everybody plays at the end of the phrase
  o.push({ p: m('C4'), b: 24, d: 1, v: 0.8, h: 1 })
  o.push({ p: m('E4'), b: 24, d: 1, v: 0.8, h: 1 })
  o.push({ p: m('G4'), b: 24, d: 1, v: 0.8, h: 1 })
  o.push({ p: m('C5'), b: 24, d: 1, v: 0.85, h: 1 })
  o.push({ p: m('C2'), b: 24, d: 1, v: 0.7, h: -1 })
  o.push({ p: m('C3'), b: 24, d: 1, v: 0.6, h: -1 })
  return o
}

/**
 * A piece, with its gestures planned.
 *
 * How long a gesture lasts is the one editorial decision here, and it is the
 * difference between conducting and playing. At about a second each, one
 * movement of your hand released a whole bar of music: the piece lurched
 * forward and your hands were plainly not the thing making the notes. At
 * about half a second you are moving roughly twice a second — once per hand
 * if you alternate them — and what comes out is a note or a few, which is the
 * rate a cat's paws move in the video everybody has seen.
 */
function scored(p: Omit<Piece, 'gestures'> & { gestureSeconds?: number }): Piece {
  const span = spanFor(p.pulseBpm, p.gestureSeconds ?? 0.5)
  return { ...p, gestures: planGestures(p.notes, p.loopAt, p.pulsesPerBar, span).at }
}

export const PIECES: Piece[] = [
  scored({
    id: 'bach-prelude',
    title: 'Prelude in C',
    composer: 'J.S. Bach',
    short: 'Bach',
    blurb: 'Sixteen notes a bar, all the same shape, thirty-five bars of it.',
    pulseBpm: 60, pulsesPerBar: bachPrelude.pulsesPerBar, stride: 1,
    loopAt: bachPrelude.loopAt, release: 0.4,
    accent: '#5ff2d6', accent2: '#1b6b7a',
    resonance: [48, 55, 60, 64, 67, 72, 79],
    notes: bachPrelude.notes,
  }),
  scored({
    id: 'minuet-g',
    title: 'Minuet in G',
    composer: 'C. Petzold',
    short: 'Petzold',
    blurb: 'A dance from the Anna Magdalena notebook. Both halves of it.',
    pulseBpm: 96, pulsesPerBar: minuetG.pulsesPerBar, stride: 1,
    loopAt: minuetG.loopAt, release: 0.26,
    accent: '#ffe27a', accent2: '#7a5a12',
    resonance: [43, 50, 55, 59, 62, 67, 74],
    notes: minuetG.notes,
  }),
  scored({
    id: 'fur-elise',
    title: 'Für Elise',
    composer: 'L. van Beethoven',
    short: 'Beethoven',
    blurb: 'Everyone knows the first eight bars. There are a hundred and five.',
    pulseBpm: 100, pulsesPerBar: furElise.pulsesPerBar, stride: 1,
    loopAt: furElise.loopAt, release: 0.3,
    accent: '#ffb3d1', accent2: '#8a3a6b',
    resonance: [45, 52, 57, 60, 64, 69, 76],
    notes: furElise.notes,
  }),
  scored({
    id: 'moonlight',
    title: 'Moonlight Sonata',
    composer: 'L. van Beethoven',
    short: 'Beethoven',
    blurb: 'Slow. Very slow. All sixty-nine bars of somewhere sad to be.',
    pulseBpm: 52, pulsesPerBar: moonlight.pulsesPerBar, stride: 1,
    loopAt: moonlight.loopAt, release: 1.5,
    accent: '#9fb8ff', accent2: '#26356e',
    resonance: [37, 49, 56, 61, 64, 68, 73],
    notes: moonlight.notes,
  }),
  scored({
    id: 'pathetique',
    title: 'Pathétique II',
    composer: 'L. van Beethoven',
    short: 'Beethoven',
    blurb: 'The Adagio cantabile. The most singing tune he ever wrote down.',
    pulseBpm: 60, pulsesPerBar: pathetique.pulsesPerBar, stride: 1,
    loopAt: pathetique.loopAt, release: 0.9,
    accent: '#d9a8ff', accent2: '#4b2a6b',
    resonance: [44, 51, 56, 60, 63, 68, 75],
    notes: pathetique.notes,
  }),
  scored({
    id: 'sonata-facile',
    title: 'Sonata Facile',
    composer: 'W.A. Mozart',
    short: 'Mozart',
    blurb: 'K.545. Mozart called it for beginners. Mozart was being unkind.',
    pulseBpm: 116, pulsesPerBar: sonataFacile.pulsesPerBar, stride: 1,
    loopAt: sonataFacile.loopAt, release: 0.24,
    accent: '#8ee6ff', accent2: '#14566b',
    resonance: [48, 55, 60, 64, 67, 72, 79],
    notes: sonataFacile.notes,
  }),
  scored({
    id: 'alla-turca',
    title: 'Rondo alla Turca',
    composer: 'W.A. Mozart',
    short: 'Mozart',
    blurb: 'A janissary band, arriving. One hundred and twenty-eight bars of it.',
    pulseBpm: 120, pulsesPerBar: allaTurca.pulsesPerBar, stride: 1,
    loopAt: allaTurca.loopAt, release: 0.2,
    accent: '#ff9d5c', accent2: '#7a3a12',
    resonance: [45, 52, 57, 61, 64, 69, 76],
    notes: allaTurca.notes,
  }),
  scored({
    id: 'entertainer',
    title: 'The Entertainer',
    composer: 'S. Joplin',
    short: 'Joplin',
    blurb: 'Ragtime. The tune lands between the beats; the bass never does.',
    pulseBpm: 100, pulsesPerBar: entertainer.pulsesPerBar, stride: 1,
    loopAt: entertainer.loopAt, release: 0.2,
    accent: '#ffa64d', accent2: '#8a4a12',
    resonance: [48, 55, 60, 64, 67, 72, 79],
    notes: entertainer.notes,
  }),
  scored({
    id: 'mapleleaf',
    title: 'Maple Leaf Rag',
    composer: 'S. Joplin',
    short: 'Joplin',
    blurb: 'The one that sold half a million copies. Tempo di marcia.',
    pulseBpm: 100, pulsesPerBar: mapleLeaf.pulsesPerBar, stride: 1,
    loopAt: mapleLeaf.loopAt, release: 0.18,
    accent: '#b5e853', accent2: '#3e6b12',
    resonance: [44, 51, 56, 60, 63, 68, 75],
    notes: mapleLeaf.notes,
  }),
  scored({
    id: 'mountain-king',
    title: 'Mountain King',
    composer: 'E. Grieg',
    short: 'Grieg',
    blurb: 'Start it as slowly and quietly as you dare. Do not stay there.',
    pulseBpm: 132, pulsesPerBar: mountainKing.pulsesPerBar, stride: 1,
    loopAt: mountainKing.loopAt, release: 0.22,
    accent: '#c69bff', accent2: '#4a2a80',
    resonance: [35, 47, 54, 59, 62, 66, 71],
    notes: mountainKing.notes,
  }),
  scored({
    id: 'chopsticks',
    title: 'Chopsticks',
    composer: 'trad.',
    short: 'trad.',
    blurb: 'A waltz for the sides of both hands. Deeply silly. Weirdly hard.',
    pulseBpm: 150, pulsesPerBar: 3, stride: 1, loopAt: 27, release: 0.18,
    accent: '#8ef07a', accent2: '#2c6b24',
    resonance: [48, 55, 60, 64, 67, 72, 76],
    notes: chopsticks(),
  }),
]
